# Generated by Django 5.2.4 on 2025-11-30 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Patient age (0-120)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('position', models.CharField(choices=[('PA', 'Posteroanterior'), ('AP', 'Anteroposterior')], max_length=2)),
                ('image', models.ImageField(upload_to='xrays/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('is_analyzed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'X-Ray',
                'verbose_name_plural': 'X-Rays',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Prediction confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='xray.xray')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-confidence'],
            },
        ),
    ]
